[package]
name = "bimc"
version = "0.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2"
log = "0.4"
rand = "0.8"
getopts = "0.2"
env_logger = "0.9"
openssl-probe = "0.1"
openssl = { version = "0.10", features = ["vendored"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
