[package]
name = "bimc"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
log = "0.4"
env_logger = "0.9"
url = "2"
openssl = { version = "0.10", features = ["vendored"] }
clap = { version = "3.2", features = ["derive"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
