[package]
name = "bimc"
version = "0.7.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
serde_json = "1"
log = "0.4"
env_logger = "0.9"
url = "2"
openssl = { version = "0.10", features = ["vendored"] }
clap = { version = "3.2", features = ["derive"] }
minreq = { version = "2.6.0", features = ["https-bundled-probe", "json-using-serde"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
